// Package sandbox contains the domain/service layer for sandbox lifecycle
// management: create/exec/delete orchestration, the DB-backed distributed
// lock, and coordination across the Repository, DockerClient and Storage
// interfaces implemented elsewhere.
package sandbox

import (
	"time"

	"github.com/google/uuid"
)

// Sandbox is the domain representation of a sandbox row. There is no stored
// "state" - whether a sandbox is currently executing is a live fact about
// Docker (see Service.ensureNotExecuting), not something persisted here.
type Sandbox struct {
	ID        uuid.UUID
	Image     string
	Workspace string // directory inside the container to persist
	CreatedAt time.Time
}

// NewSandbox is the input to Repository.CreateSandbox. ID is generated by
// Service before the insert so the container/volume names and the NFS
// location can all be derived deterministically from it later.
type NewSandbox struct {
	ID        uuid.UUID
	Image     string
	Workspace string
}
